ARG BASE_IMAGE=nvidia/cuda:11.1.1-runtime-ubuntu20.04
FROM ${BASE_IMAGE}
ARG BASE_IMAGE=nvidia/cuda:11.1.1-runtime-ubuntu20.04
ARG MODEL_SERVER=fastapi

LABEL description="Base container for GPU models"

USER root

RUN apt-get update && apt-get install -y htop dnsutils bc vim curl
RUN pip install configparser

RUN if [ "$MODEL_SERVER" = "fastapi" ]; then \
        apt-get update && apt-get install -y wget software-properties-common debconf-utils python3-distutils ; \
        # Install python3.9
        DEBIAN_FRONTEND=noninteractive; add-apt-repository -y ppa:deadsnakes/ppa; apt install -y python3.9; update-alternatives --install /usr/bin/python python /usr/bin/python3.9 1;\
        # Install pip
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py; python get-pip.py; rm -f get-pip.py; \
        # Install pytorch with GPU support
        pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html; \
        echo "PATH=/usr/local/cuda/bin\${PATH:+:\${PATH}}" >> /etc/environment; \
        echo "LD_LIBRARY_PATH=/usr/local/cuda/lib64\${LD_LIBRARY_PATH:+:\${LD_LIBRARY_PATH}}" >> /etc/environment; \
        # Install other python libraries
        pip install transformers ; \
    fi
