#FROM nvidia/cuda:11.1.1-runtime-ubuntu20.04
FROM nvidia/cuda:12.3.1-runtime-ubuntu22.04

LABEL description="Base container for GPU models"

RUN apt-get update && apt-get install -y htop vim wget curl software-properties-common debconf-utils python3-distutils dnsutils bc unzip

# Install python3.9
RUN add-apt-repository -y ppa:deadsnakes/ppa; DEBIAN_FRONTEND=noninteractive apt install -y python3.9; update-alternatives --install /usr/bin/python python /usr/bin/python3.9 1
RUN cp -vf /usr/bin/python3 /usr/bin/python

# Install pip
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py; python3 get-pip.py; rm -f get-pip.py

# Install pytorch with GPU support
#RUN pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
RUN pip3 install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu121

RUN echo "PATH=/usr/local/cuda/bin\${PATH:+:\${PATH}}" >> /etc/environment
RUN echo "LD_LIBRARY_PATH=/usr/local/cuda/lib64\${LD_LIBRARY_PATH:+:\${LD_LIBRARY_PATH}}" >> /etc/environment

# Install other python libraries
RUN pip3 install transformers configparser

# Install AWS cli
RUN curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o "awscliv2.zip"; unzip awscliv2.zip; ./aws/install; cp -f /usr/local/bin/aws /bin/aws; rm -rf ./aws; rm -f awscli2.zip; aws --version

