ARG BASE_IMAGE=python:3.9

FROM ${BASE_IMAGE}
ARG BASE_IMAGE=python:3.9
ARG MODEL_SERVER=fastapi


LABEL description="Base container for CPU models"

USER root

RUN apt-get update && apt-get install -y htop dnsutils bc vim

RUN pip install configparser

RUN if [ "$MODEL_SERVER" = "fastapi" ]; then \
        pip install torch transformers; \
        echo "alias ll='ls -alh --color=auto'" >> /root/.bashrc; \
    else \
        apt-get update && apt-get install -y curl; \
    fi
